from __future__ import annotations

import json
import sys
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
ROSTER = ROOT / "swarm" / "roster.json"

# The documentation generator owns exactly these files inside this directory.
# It must never create, modify, or delete anything outside it.
GEN_DIR_REL = "web/docs/_generated"
GEN_SUFFIX = ".md"

# Division display name -> generated division filename (stem).
DIVISION_PAGES: dict[str, str] = {
    "Affiliate Marketing": "affiliate-marketing.md",
    "Automated Advertising": "automated-advertising.md",
    "Consumer Marketing Analytics": "consumer-marketing-analytics.md",
}

REQUIRED_FIELDS = (
    "id",
    "title",
    "tier",
    "division",
    "reports_to",
    "kind",
    "description",
    "mission",
    "responsibilities",
    "deliverables",
    "children",
)

HEADER = (
    "<!--\n"
    "  DO NOT EDIT THIS FILE BY HAND.\n"
    "  Generated by scripts/build_docs.py from swarm/roster.json.\n"
    "  Regenerate:  python3 scripts/build_docs.py\n"
    "  Check drift: python3 scripts/build_docs.py --check\n"
    "-->\n"
)


def fail(message: str) -> None:
    print(f"ERROR: {message}")
    raise SystemExit(1)


def load_roster() -> dict[str, Any]:
    return json.loads(ROSTER.read_text(encoding="utf-8"))


def validate_structure(payload: dict[str, Any]) -> list[dict[str, Any]]:
    """Fail fast if the roster does not match the shape this generator expects."""
    if "version" not in payload:
        fail("roster.json missing 'version'")
    agents = payload.get("agents")
    if not isinstance(agents, list) or not agents:
        fail("roster.json 'agents' must be a non-empty list")

    ids = [a.get("id") for a in agents]
    if len(ids) != len(set(ids)):
        fail("roster.json has duplicate agent ids")
    id_set = set(ids)

    for a in agents:
        for field in REQUIRED_FIELDS:
            if field not in a:
                fail(f"agent {a.get('id', '<unknown>')} missing field '{field}'")
        for field in ("responsibilities", "deliverables", "children"):
            if not isinstance(a[field], list):
                fail(f"agent {a['id']} field '{field}' must be a list")
        parent = a["reports_to"]
        if parent is not None and parent not in id_set:
            fail(f"agent {a['id']} reports_to unknown id '{parent}'")
        for child in a["children"]:
            if child not in id_set:
                fail(f"agent {a['id']} references unknown child '{child}'")

    roots = [a["id"] for a in agents if a["reports_to"] is None]
    if roots != ["worldwide-marketing-orchestrator"]:
        fail(f"expected a single orchestrator root, found: {roots}")

    for division in DIVISION_PAGES:
        members = [a for a in agents if a["division"] == division]
        if not members:
            fail(f"no agents found for expected division '{division}'")
        if not any(a["tier"] == "lead" for a in members):
            fail(f"division '{division}' has no lead")

    return agents


def md_list(items: list[str]) -> str:
    return "\n".join(f"- {item}" for item in items)


def agent_section(a: dict[str, Any], by_id: dict[str, dict[str, Any]]) -> str:
    lines: list[str] = []
    lines.append(f"## {a['title']}")
    lines.append("")
    lines.append(f"- **Agent ID:** `{a['id']}`")
    lines.append(f"- **Tier:** {a['tier']}")
    lines.append(f"- **Division:** {a['division']}")
    parent = a["reports_to"]
    if parent is None:
        lines.append("- **Reports to:** none (top-level orchestrator)")
    else:
        lines.append(f"- **Reports to:** {by_id[parent]['title']} (`{parent}`)")
    lines.append("")
    lines.append(f"**Description:** {a['description']}")
    lines.append("")
    lines.append(f"**Mission:** {a['mission']}")
    lines.append("")
    lines.append("**Responsibilities:**")
    lines.append("")
    lines.append(md_list(a["responsibilities"]))
    lines.append("")
    lines.append("**Deliverables:**")
    lines.append("")
    lines.append(md_list(a["deliverables"]))
    if a["children"]:
        child_items = [f"{by_id[c]['title']} (`{c}`)" for c in a["children"]]
        lines.append("")
        lines.append("**Delegates to:**")
        lines.append("")
        lines.append(md_list(child_items))
    return "\n".join(lines)


def roster_summary(agents: list[dict[str, Any]], version: str) -> str:
    orchestrators = [a for a in agents if a["tier"] == "orchestrator"]
    leads = [a for a in agents if a["tier"] == "lead"]
    specialists = [a for a in agents if a["tier"] == "specialist"]

    lines: list[str] = []
    lines.append("## Roster at a glance")
    lines.append("")
    lines.append(
        f"Roster version **{version}** defines **{len(agents)} agents**: "
        f"{len(orchestrators)} orchestrator, {len(leads)} division leads, and "
        f"{len(specialists)} specialists."
    )
    lines.append("")
    lines.append("| Agent | Agent ID | Tier | Division | Reports to |")
    lines.append("|---|---|---|---|---|")
    for a in agents:
        parent = a["reports_to"]
        reports = "—" if parent is None else f"`{parent}`"
        lines.append(
            f"| {a['title']} | `{a['id']}` | {a['tier']} | {a['division']} | {reports} |"
        )
    return "\n".join(lines)


def division_page(division: str, agents: list[dict[str, Any]], by_id: dict[str, dict[str, Any]]) -> str:
    members = [a for a in agents if a["division"] == division]  # roster order preserved
    sections = [agent_section(a, by_id) for a in members]
    return "\n\n".join(sections)


def normalized(content: str) -> str:
    return content.rstrip() + "\n"


def expected_files(payload: dict[str, Any], agents: list[dict[str, Any]]) -> dict[str, str]:
    by_id = {a["id"]: a for a in agents}
    version = payload["version"]
    files: dict[str, str] = {}

    files[f"{GEN_DIR_REL}/roster-summary.md"] = normalized(
        HEADER + "\n" + roster_summary(agents, version)
    )
    for division, filename in DIVISION_PAGES.items():
        files[f"{GEN_DIR_REL}/{filename}"] = normalized(
            HEADER + "\n" + division_page(division, agents, by_id)
        )
    return files


def stale_files(expected: dict[str, str]) -> list[str]:
    base = ROOT / GEN_DIR_REL
    if not base.exists():
        return []
    stale: list[str] = []
    for path in base.glob(f"*{GEN_SUFFIX}"):
        rel = path.relative_to(ROOT).as_posix()
        if rel not in expected:
            stale.append(rel)
    return sorted(stale)


def run_check(expected: dict[str, str]) -> int:
    problems: list[str] = []
    for rel, content in sorted(expected.items()):
        path = ROOT / rel
        if not path.exists():
            problems.append(f"MISSING  {rel}")
        elif path.read_text(encoding="utf-8") != content:
            problems.append(f"DRIFT    {rel}")
    for rel in stale_files(expected):
        problems.append(f"STALE    {rel}")
    if problems:
        print("Documentation drift detected (run: python3 scripts/build_docs.py):")
        for problem in problems:
            print(f"  {problem}")
        return 1
    print(f"CHECK OK: {len(expected)} generated documentation files match swarm/roster.json.")
    return 0


def write_all(expected: dict[str, str]) -> list[str]:
    for rel, content in expected.items():
        path = ROOT / rel
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
    removed = stale_files(expected)
    for rel in removed:
        (ROOT / rel).unlink()
    return removed


def main() -> None:
    payload = load_roster()
    agents = validate_structure(payload)
    expected = expected_files(payload, agents)

    if "--check" in sys.argv[1:]:
        raise SystemExit(run_check(expected))

    removed = write_all(expected)
    print(f"Generated {len(expected)} documentation file(s) under {GEN_DIR_REL}/.")
    if removed:
        print(f"Removed {len(removed)} stale generated file(s):")
        for rel in removed:
            print(f"  {rel}")


if __name__ == "__main__":
    main()
